app/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import CustomLoginView, CustomLogoutView, crear_usuario,cambiar_contrasena_usuario,lista_usuarios,cambiar_contraseña
app_name = 'accounts_app'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('crear_usuario/', crear_usuario, name='crear_usuario'),
    path('cambiar-contrasena/', cambiar_contraseña, name='cambiar_contraseña'),
    path('admin/usuarios/', lista_usuarios, name='lista_usuarios'),
    path('admin/cambiar-contrasena/<int:user_id>/',cambiar_contrasena_usuario, name='cambiar_contrasena_usuario'),
]

stb_sonda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),

    path('accounts/', include('accounts.urls')),
    path('', views.home, name='home'),
    
    path('matrix/', include('matrix.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="header d-flex">
    <div class="d-flex flex-column">
        <h1>QC Seguimiento Revisiones</h1>
    <div>
        <p><strong>Usuario:</strong> {{ request.user.nombre }} {{ request.user.apellido }} <strong>Cargo:</strong> {{ request.user.cargo }} <strong>Equipo:</strong> {{ request.user.equipo_nuevo }}</p>
    </div>
    </div>
    <div class="group-btn">
        <div class="d-flex align-items-center gap-3">
            <!-- Menú de engranaje -->
            <div class="dropdown me-3">
                <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="settingsDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    ⚙️
                </button>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="settingsDropdown">
                    <li><a class="dropdown-item" href="{% url 'accounts_app:cambiar_contraseña' %}">Cambiar contraseña</a></li>
                </ul>
            </div>
        </div>
        <a href="{% url 'home' %}" class="home-btn">Home</a>
    <form method="post" action="{% url 'accounts_app:logout' %}">
        {% csrf_token %}
        
        <button type="submit" class="logout-btn">Cerrar sesión</button>
    </form>
    </div>
    
</div>